---
# Setup drivers and Docker for a GPU instance
- hosts: gpu
  become: true
  tasks:
    - name: Install Nvidia drivers
      include_role:
          name: nvidia_driver

    - name: Install Nvidia Docker
      include_role:
          name: nvidia_docker

    - name: Make sure containerd config folder exists
      file:
        path: /var/lib/rancher/rke2/agent/etc/containerd
        state: directory

    # ref: https://dev.to/mweibel/add-nvidia-gpu-support-to-k3s-with-containerd-4j17
    - name: Place containerd config
      copy:
        src: config.toml.tmpl
        dest: /var/lib/rancher/rke2/agent/etc/containerd/config.toml.tmpl

    - name: Restart rke
      systemd:
        state: restarted
        name: "rke2-agent"
